In [1]:
import sys

import tensorflow.keras
import pandas as pd
import sklearn as sk
import tensorflow as tf
import platform

print(f"Python Platform: {platform.platform()}")
print(f"Tensor Flow Version: {tf.__version__}")
print(f"Keras Version: {tensorflow.keras.__version__}")
print()
print(f"Python {sys.version}")
print(f"Pandas {pd.__version__}")
print(f"Scikit-Learn {sk.__version__}")
gpu = len(tf.config.list_physical_devices('GPU'))>0
print("GPU is", "available" if gpu else "NOT AVAILABLE")

Python Platform: macOS-13.1-arm64-arm-64bit
Tensor Flow Version: 2.11.0
Keras Version: 2.11.0

Python 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:25:29) [Clang 14.0.6 ]
Pandas 1.5.2
Scikit-Learn 1.2.0
GPU is available


In [2]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

2023-01-18 15:46:44.249569: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2023-01-18 15:46:44.586647: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1/1 [==============================] - 2s 2s/step
[[6.7081540e-03 9.9317920e-01 6.2475081e-08 1.1254427e-04]]
1/1 [==============================] - 0s 26ms/step
[[3.8622323e-01 4.1281101e-01 2.0087169e-01 9.4089053e-05]]
1/1 [==============================] - 0s 23ms/step
[[5.3084081e-01 3.8990027e-01 7.9141669e-02 1.1727547e-04]]
1/1 [==============================] - 0s 24ms/step
[[1.6528462e-01 8.1845731e-01 1.6225966e-02 3.2058007e-05]]
1/1 [==============================] - 0s 24ms/step
[[4.1559127e-01 5.3573245e-01 4.8634741e-02 4.1549050e-05]]
1/1 [==============================] - 0s 23ms/step
[[4.9397224e-01 4.9990967e-01 6.0484521e-03 6.9695678e-05]]
1/1 [==============================] - 0s 25ms/step
[[1.6497564e-01 8.2867128e-01 6.3373493e-03 1.5750338e-05]]
1/1 [==============================] - 0s 24ms/step
[[4.1571558e-01 5.1262593e-01 7.1595617e-02 6.2944644e-05]]
1/1 [==============================] - 0s 23ms/step
[[4.8312747e-01 4.9554855e-01 2.1250445e-02 7.3624789e

KeyboardInterrupt: 